# Generated by Django 5.2.8 on 2026-01-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listed_by',
            field=models.CharField(blank=True, null=True),
        ),
    ]
