# Generated by Django 5.2.8 on 2026-01-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_listed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listed_by',
            field=models.CharField(blank=True, default=''),
        ),
    ]
