# Generated by Django 5.2.8 on 2026-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_listed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
