# Generated by Django 5.2.8 on 2026-01-10 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_listed_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='profiles/default.png', upload_to='profiles/')),
                ('address_line', models.CharField(blank=True, default='Not provided', max_length=255)),
                ('pin_code', models.CharField(blank=True, default='000000', max_length=10)),
                ('state', models.CharField(blank=True, default='Not provided', max_length=100)),
                ('country', models.CharField(blank=True, default='Not provided', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='Not provided', max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
