# Generated by Django 5.2.8 on 2026-01-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profile_images/'),
        ),
    ]
