# Generated by Django 5.2.8 on 2026-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, default='https://www.pngall.com/wp-content/uploads/5/Profile-Avatar-PNG-Picture.png', upload_to='profile_images/'),
        ),
    ]
